Use Teamredminer

diff --git a/mining-exporter/cgi-bin/metrics b/mining-exporter/cgi-bin/metrics
--- a/mining-exporter/cgi-bin/metrics
+++ b/mining-exporter/cgi-bin/metrics
@@ -18,22 +18,20 @@ along with this program.  If not, see <http://www.gnu.org/licenses/>.
 '
 
 trm() {
-	local resp=`echo -n 'summary+devdetails+gpucount' | nc -w 10 $1 $2 | sed 's/,/\n/g; s/|//g' | grep '^Count\|^Elapsed'`
-	[ -z "$resp" ] && return -1
-	export $resp
-	for (( i=0; i<$Count; i++ ))
-	do
-        	export `echo -n 'gpu|'$i | nc $1 $2 | sed 's/ //g; s/,/\n/g' | grep '^Accepted\|^Rejected\|Temperature\|FanPercent\|MHS30s\|HardwareErrors'`
-		local l="{gpu=\"$i\" host=\"$1:$2\"}"
-        	echo "accepted$l $Accepted
-rejected$l $Rejected
-temperature$l $Temperature
-fan$l $FanPercent
-hashrate$l $MHS30s
-hw$l $HardwareErrors"
-	done
-	echo "uptime{host=\"$1:$2\"} $Elapsed"
-	unset Count Accepted Rejected Temperature FanPercent MHS30s HardwareErrors Elapsed
+        local resp=( `echo -n '{"command":"summary+gpucount"}' | nc -w 10 $1 $2 | jq '.summary.SUMMARY[0].Elapsed, .gpucount.GPUS[0].Count'` )
+        local uptime=${resp[0]}
+        local count=${resp[1]}
+        [ "${#resp[@]}" -eq 2 ] || return -1
+        local result=()
+        for (( i=0; i<$count; i++ ))
+        do
+                local gpu=( `echo -n '{"command":"gpu","parameter":'$i'}' | nc -w 2 $1 $2 | jq '.GPU[0] | .Accepted, .Rejected, .Temperature, ."Fan Percent", ."MHS 30s", ."Hardware Errors"'` )
+                local l="{gpu=\"$i\" host=\"$1:$2\"}"
+                [ "${#gpu[@]}" -eq 6 ] || return -1
+                result+=( "accepted$l ${gpu[0]}" "rejected$l ${gpu[1]}" "temperature$l ${gpu[2]}" "fan$l ${gpu[3]}" "hashrate$l ${gpu[4]}" "hw$l ${gpu[5]}" )
+        done
+        printf '%s\n' "${result[@]}"
+        echo "uptime{host=\"$1:$2\"} $uptime"
 }
 
 t-rex() {
